nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "8000:80"
node1:
    build: ./web
    links:
        - redis
    ports:
        - "3000"
node2:
    build: ./web
    links:
        - redis
    ports:
        - "3000"
node3:
    build: ./web
    links:
        - redis
    ports:
        - "3000"
redis:
    image: redis
    ports:
        - "6379"